# Generated by Django 4.0.1 on 2022-05-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_moto_nombre_marca_moto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dvrun_cliente',
            field=models.IntegerField(verbose_name='digito verificador de rut del cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono_cliente',
            field=models.IntegerField(verbose_name='Telefono del cliente'),
        ),
        migrations.AlterField(
            model_name='moto',
            name='cilindrica',
            field=models.IntegerField(verbose_name='cilindrica de la moto'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='dvrun_vendedor',
            field=models.IntegerField(verbose_name='digito verificador de rut del vendedor'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='sueldo_vendedor',
            field=models.IntegerField(verbose_name='Sueldo del vendedor'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='telefono_vendedor',
            field=models.IntegerField(verbose_name='Telefono del vendedor'),
        ),
    ]
