# Generated by Django 4.0.4 on 2022-05-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_categoria_vehiculo_delete_cliente_delete_moto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='Servicio',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Servicio'),
        ),
    ]
