# Generated by Django 4.0.4 on 2022-06-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_vehiculo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='hora',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='motocicletas'),
        ),
    ]
